version: '3.7'

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.4.0
    hostname: wazuh.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - API_USERNAME=wazuh
      - API_PASSWORD=wazuh
      - WAZUH_CLUSTER_NAME=wazuh-cluster
      - WAZUH_CLUSTER_NODE_NAME=node-01
      - WAZUH_CLUSTER_NODE_TYPE=master
      - WAZUH_CLUSTER_KEY=1a2b3c4d5e6f7g8h9i0j
    volumes:
      - ./configs/ossec.conf:/var/ossec/etc/ossec.conf:ro
      - ./configs/custom_rules.xml:/var/ossec/ruleset/custom_rules.xml:ro
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - wazuh_backup:/var/ossec/backup
    depends_on:
      - wazuh.indexer
      - wazuh.db

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.4.0
    hostname: wazuh.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=SecretPassword"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/usr/share/opensearch/data
      - ./configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.4.0
    hostname: wazuh.dashboard
    restart: always
    ports:
      - "5601:5601"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh.manager:55000
      - API_USERNAME=wazuh
      - API_PASSWORD=wazuh
    volumes:
      - ./configs/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/config
      - wazuh-dashboard-data:/usr/share/wazuh-dashboard/data
    depends_on:
      - wazuh.indexer
      - wazuh.manager

  wazuh.db:
    image: postgres:13
    hostname: wazuh.db
    restart: always
    environment:
      - POSTGRES_DB=wazuh
      - POSTGRES_USER=wazuh
      - POSTGRES_PASSWORD=wazuh-db-password
    volumes:
      - wazuh-db-data:/var/lib/postgresql/data

volumes:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  wazuh_backup:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-data:
  wazuh-db-data:

networks:
  default:
    driver: bridge
